development:
  adapter: postgresql
  encoding: unicode
  database: timetracker_development_3
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: timetracker_test_3
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: timetracker_production
  pool: 5
